# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EMNewton0 <- function(maxiterEM, tolEM, alpha, zeta, x, delta, t, tevent, num_class, d, lambda_EM, loglik_EM, postweight, printplot) {
    .Call('_lcphR_EMNewton0', PACKAGE = 'lcphR', maxiterEM, tolEM, alpha, zeta, x, delta, t, tevent, num_class, d, lambda_EM, loglik_EM, postweight, printplot)
}

EMNewton <- function(maxiterEM, tolEM, maxiterNewton, tolNewton, alpha, zeta, x, delta, t, tevent, num_class, d, tau, lambda_EM, loglik_EM, postweight, printplot) {
    .Call('_lcphR_EMNewton', PACKAGE = 'lcphR', maxiterEM, tolEM, maxiterNewton, tolNewton, alpha, zeta, x, delta, t, tevent, num_class, d, tau, lambda_EM, loglik_EM, postweight, printplot)
}

newton <- function(maxiterNewton, tolNewton, alpha, zeta, x, delta, t, tevent, num_class, tau, lambda_EM, loglik_EM) {
    .Call('_lcphR_newton', PACKAGE = 'lcphR', maxiterNewton, tolNewton, alpha, zeta, x, delta, t, tevent, num_class, tau, lambda_EM, loglik_EM)
}

lambda_EM <- function(zeta, x, t, tevent, num_class, tau) {
    .Call('_lcphR_lambda_EM', PACKAGE = 'lcphR', zeta, x, t, tevent, num_class, tau)
}

loglik_EM <- function(alpha, zeta, x, delta, t, tevent, num_class, d, d1, d2, tau) {
    .Call('_lcphR_loglik_EM', PACKAGE = 'lcphR', alpha, zeta, x, delta, t, tevent, num_class, d, d1, d2, tau)
}

numericInfo <- function(alpha, zeta, x, delta, t, tevent, num_class, l0, tau, epsilon, lambda_EM, loglik_EM, postweight) {
    .Call('_lcphR_numericInfo', PACKAGE = 'lcphR', alpha, zeta, x, delta, t, tevent, num_class, l0, tau, epsilon, lambda_EM, loglik_EM, postweight)
}

postweight <- function(alpha, zeta, x, delta, t, tevent, num_class, d) {
    .Call('_lcphR_postweight', PACKAGE = 'lcphR', alpha, zeta, x, delta, t, tevent, num_class, d)
}

varestcpp <- function(zeta, delta, chaz, tau, p, x, tevent) {
    .Call('_lcphR_varestcpp', PACKAGE = 'lcphR', zeta, delta, chaz, tau, p, x, tevent)
}

